### ISSUE TITLE
Problems of installation

### ISSUE THREAD

**Issue by Jim1705** [BroVic/RQDAassist#10]
Dear BroVic

I have a problem of installation of RQDAassist.

I just install the last versions of R (I had before a version 3) and Rstudio 
I also installed Rtools4

I wrote these different commands

write('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)
install.packages("devtools")
devtools::install_github("BroVic/RQDAassist")

for the installation of RQDAassist, it seems I have a problem with cli

devtools::install_github("BroVic/RQDAassist")
Downloading GitHub repo BroVic/RQDAassist@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                        
2: CRAN packages only         
3: None                       
4: cli (3.1.1 -> 3.2.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
cli (3.1.1 -> 3.2.0) [CRAN]
Installing 1 packages: cli
Installation du package dans ‘C:/Users/jeanm/OneDrive/Documents/R/win-library/4.1’
(car ‘lib’ n'est pas spécifié)

  Une version binaire est disponible mais la version du source est plus récente:
    binary source needs_compilation
cli  3.1.1  3.2.0              TRUE

installation du package source ‘cli’

trying URL 'https://cran.rstudio.com/src/contrib/cli_3.2.0.tar.gz'
Content type 'application/x-gzip' length 493192 bytes (481 KB)
downloaded 481 KB

* installing *source* package 'cli' ...
** package 'cli' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/jeanm/OneDrive/Documents/R/win-library/4.1/cli'
* restoring previous 'C:/Users/jeanm/OneDrive/Documents/R/win-library/4.1/cli'
Avis dans file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problème lors de la copie de C:\Users\jeanm\OneDrive\Documents\R\win-library\4.1\00LOCK-cli\cli\libs\x64\cli.dll vers C:\Users\jeanm\OneDrive\Documents\R\win-library\4.1\cli\libs\x64\cli.dll: Permission denied

The downloaded source packages are in
	‘C:\Users\jeanm\AppData\Local\Temp\RtmpCMY9bn\downloaded_packages’
Error: Failed to install 'RQDAassist' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE
In addition: Warning message:
In i.p(...) : installation of package ‘cli’ had non-zero exit status 

Best 

Jim

**Comment by BroVic** [comment]
Hello @Jim1705 

I think you should install cli separately - I have experienced this problem before. But generally, RQDAassist has not yet been full tested for Linux. You would have to install gtk-dev2.0 in bash, before trying to get this to work. I can help you to troubleshoot though. Let me know how it goes.

**Comment by BroVic** [comment]
@Jim1705 

In the absence of any further comment, I am closing this issue.
