### ISSUE TITLE
Installing RQDA Assist

### ISSUE THREAD

**Issue by krisruygrok** [BroVic/RQDAassist#17]
Dear Victor, 

I am emailing you with a question about RQDA assist. I am not a user of Rstudio myself, but used it only for RQDA. Now I want to reinstall RQDA again but I have some troubles that I hope you can help me with. 

I think I have successfully downloaded RQDAassist, see attachment. 
 
![pic](https://user-images.githubusercontent.com/121096804/208658749-2083d06f-d623-4e4d-a432-3456bc740b3f.jpg)

I cant figure out what I need to do after that, however.  Could you please help me out in simple language 😊 ? 

Your manual says something about binary install and source install but I really don’t know what it all means and how to deal with it. 

Many thanks in advance!

**Comment by BroVic** [comment]
Hello @krisruygrok 

Please install R 4.1.3 from [here](https://cran.r-project.org/bin/windows/base/old/4.1.3/R-4.1.3-win.exe) and try again. 

Go to `Tools` > `Global Options` and set the R version to 4.1.3, then close R Studio and reopen it to use it that version of R. Then try the RQDA  installation again following the instructions in the README.

**Comment by BroVic** [comment]
@krisruygrok 

If there are no more comments, I will be closing this issue. If you need further help on this particular issue, feel free to reopen it.
