### ISSUE TITLE
package ‘RGtk2’ not installed because it is not built for UCRT

### ISSUE THREAD

**Issue by Joseph1Otoo** [BroVic/RQDAassist#19]
Hello BroVic,

I followed the installations steps and I have this error: 
package ‘RGtk2’ not installed because it is not built for UCRT.

I am using R version 4.2.2 and using windows for the installation.

**Comment by BroVic** [comment]
Hi, you'll have to step down to using [R 4.1.3](https://cran.r-project.org/bin/windows/base/old/$Rversion/R-$Rversion-win.exe) for now. If you don't already have it, you also need [Rtools40](https://github.com/r-windows/rtools-installer/releases/download/2022-02-06/rtools40-x86_64.exe). (Use the links to download)

**Comment by mazepse** [comment]
Dear Vic
Hello and Happy New Year!
Tell me please where is my bad?
while running 
> RQDAassist::install()
i Get: 
Installing 'cairoDevice' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/cairoDevice/cairoDevice_2.28.2.1.tar.gz
* installing *source* package 'cairoDevice' ...
** package 'cairoDevice' successfully unpacked and MD5 sums checked
** using staged installation
Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'cairoDevice'
* removing 'D:/Program Files/R/R-4.1.3/library/cairoDevice'
Done
Package already installed: gWidgets 
Installing 'gWidgetsRGtk2' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/gWidgetsRGtk2/gWidgetsRGtk2_0.0-86.tar.gz
ERROR: dependency 'cairoDevice' is not available for package 'gWidgetsRGtk2'
* removing 'D:/Program Files/R/R-4.1.3/library/gWidgetsRGtk2'
Done
Installing 'RQDA' ... 
Downloading package from url: https://cran.r-project.org/src/contrib/Archive/RQDA/RQDA_0.3-1.tar.gz
ERROR: dependency 'gWidgetsRGtk2' is not available for package 'RQDA'
* removing 'D:/Program Files/R/R-4.1.3/library/RQDA'
Done
Warning messages:
1: In i.p(...) :
  installation of package ‘C:/Users/--/AppData/Local/Temp/Rtmpa6LoBa/remotes5de0750b3f3e/cairoDevice’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/--/AppData/Local/Temp/Rtmpa6LoBa/remotes5de05a5a1baa/gWidgetsRGtk2’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘C:/Users/--/AppData/Local/Temp/Rtmpa6LoBa/remotes5de03f7231c5/RQDA’ had non-zero exit status
======

as you see r version is 4.1.3
as for r tools:
> pkgbuild::rtools_path()
[1] "C:/rtools40/usr/bin"    "C:/rtools40/ucrt64/bin"
and
RGTK2 loads ok
MANY THANKS FOR YOUR TIME!!!

**Comment by BroVic** [comment]
Did you follow the instruction in [README](https://github.com/BroVic/RQDAassist/blob/master/README.md) to try loading RGtk2 with 

```
library(RGtk2)
```

This will prompt you to automatically install the dependency Gtk+. Without it, the rest of the installation will not be successful. 

If it still fails, please run `sessionInfo()` and share the output.
