### ISSUE TITLE
Error: .onLoad failed in loadNamespace() for 'RSQLite' (on Mac OS X)

### ISSUE THREAD

**Issue by ponyBoy-dev** [BroVic/RQDAassist#5]
I'm trying to install RQDA for a couple of hours and I bumped into your package. I'm trying it on my Mac, but unfortunately it doesn't work at the moment. 

I think the installation of RQDAassist worked well because the end of the message is 
`* DONE (RQDAassist)`
But when I tried to `RQDAassist::install()`, here is what I got : 
`Error: .onLoad failed in loadNamespace() for 'RSQLite', details:
  call: get0(oNam, envir = ns)
  error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cachem/R/cachem.rdb' is corrupt
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1`

For info, I have R version 4.0.3 (2020-10-10) and RStudio version 1.3.1093, running on Mac OS Mojave 10.14.6

**Comment by BroVic** [comment]
Hello and thanks for your interest in this package. Please see #4 .

**Comment by BroVic** [comment]
@ponyBoy-dev  In addition to my last comment, do you have RSQLite installed?
